create database practise_crud;
create table returns
(
ORDERID VARCHAR(15),
RETURNED VARCHAR (3) DEFAULT 'YES'
)
;
INSERT INTO RETURNS
(ORDERID, RETURNED)
VALUES
(1, 'NO'),
(2, DEFAULT),
(3, 'NO'),
(4, 'MAY');
SELECT * FROM returns;
SELECT ORDERID FROM RETURNS;
UPDATE RETURNS
SET RETURNED = 'NO'
WHERE ORDERID = 4;
DELETE FROM RETURNS
WHERE RETURNED = 'NO';
ALTER TABLE RETURNS
ADD COLUMN RETURNDATE VARCHAR (10);
ALTER TABLE RETURNS
MODIFY RETURNDATE date;
DESCRIBE RETURNS;
truncate RETURNS;
SELECT * FROM RETURNS;
DROP TABLE RETURNS;